import type { NextPage } from 'next'
import useSWR from 'swr'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/dist/client/router'
import { Container, List, ListItem, ListItemText } from '@mui/material'

import fetcher from '../../lib/fetcher'
import { useToken } from '../../hook/useToken'
import Header from '../../components/Header'

const EventDetail: NextPage = () => {
  const router = useRouter()
  const { id } = router.query
  const {token} = useToken()

  if (!token) {
    return <>
      <Link href={'/login'}>login</Link>
    </>
  }

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const {data, error} = useSWR([`/events/${id}`, token.token], fetcher)

  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>

  return (
    <div>
      <Head>
        <title>event</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Container maxWidth="sm">
        <h1>{data.data.name}</h1>

        <List>
          <ListItem>
            <ListItemText primary={data.data.budget} />
          </ListItem>

          <ListItem>
            <ListItemText primary={data.data.start_at} />
          </ListItem>

          <ListItem>
            <ListItemText primary={data.data.end_at} />
          </ListItem>

          <ListItem>
            <ListItemText primary={data.data.max_size} />
          </ListItem>

          <ListItem>
            <ListItemText primary={data.data.location} />
          </ListItem>

          <ListItem>
            <ListItemText primary={data.data.description} />
          </ListItem>

          <ListItem>
            <ListItemText primary={data.data.organizer.name} />
          </ListItem>
        </List>
      </Container>
    </div>
  )
}

export default EventDetail
