import type { NextPage } from 'next'
import useSWR from 'swr'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/dist/client/router'
import {Layout, Typography} from 'antd'

import fetcher from '../../lib/fetcher'
import { useToken } from '../../hook/useToken'
import Header from '../../components/Header'

const { Paragraph } = Typography

const EventDetail: NextPage = () => {
  const router = useRouter()
  const { id } = router.query
  const {token} = useToken()

  if (!token) {
    return <>
      <Link href={'/login'}>login</Link>
    </>
  }

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const {data, error} = useSWR([`/events/${id}`, token.token], fetcher)

  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>

  return (
    <div>
      <Head>
        <title>event</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Layout>
        <Paragraph>
          <h1>{data.data.name}</h1>

          <ul>
            <li>{data.data.budget}</li>
            <li>{data.data.start_at}</li>
            <li>{data.data.end_at}</li>
            <li>{data.data.max_size}</li>
            <li>{data.data.location}</li>
            <li>{data.data.description}</li>
            <li>{data.data.organizer.name}</li>
          </ul>
        </Paragraph>
      </Layout>
    </div>
  )
}

export default EventDetail
