import Head from 'next/head'
import { useRouter } from 'next/dist/client/router'
import axios from 'axios'

import useStorage from '../hook/useStorage'
import React, { ReactElement, useState } from 'react'
import { Box, Button, Container, TextField } from '@mui/material'

interface LoginInfo {
  email?: string
  password?: string
}

const Login = (): ReactElement => {
  const {setItem} = useStorage()
  const [loginInfo, setLoginInfo] = useState<LoginInfo>()
  const router = useRouter();

  const onChange = (e: { target: { name: any; value: any } }) => {
    setLoginInfo({
      ...loginInfo,
      [e.target.name]: e.target.value,
    })
  }

  const onSubmit = () => {
    const body = JSON.stringify({
      email: loginInfo.email,
      password: loginInfo.password
    })
    axios.defaults.headers.common['content-type'] = 'application/json;charset=UTF-8';
    axios.post('http://localhost:8000/users/login', body).then(res => {
      if (res.data.data.token) {
        setItem('token', res.data.data.token)
        router.replace('/')
        return null
      } else {
        return null
      }
    })
  }

  return (
    <div>
      <Head>
        <title>login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="sm">
        <Box mt={2}>
          <TextField
            required
            type="email"
            name="email"
            label="email"
            onChange={onChange}
          />

          <TextField
            required
            type="password"
            name="password"
            label="password"
            onChange={onChange}
          />

          <Button onClick={onSubmit} variant="contained">login</Button>
        </Box>
      </Container>
    </div>
  )
}

export default Login
